[tool.poetry]
name = "spacytextblob"
version = "3.0"
description = "A TextBlob sentiment analysis pipeline compponent for spaCy"
authors = ["SamEdwardes <edwardes.s@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/SamEdwardes/spaCyTextBlob"
documentation = "https://spacytextblob.netlify.app/"
keywords = ["python", "spacy", "textblob", "nlp"]

[tool.poetry.dependencies]
python = "^3.6.9"
textblob = "^0.15.3"
spacy = "^3.0"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
jupyterlab = "^2.2.9"
black = "^20.8b1"
en_core_web_sm = {url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz#egg=en_core_web_sm"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
